/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as AboutImport } from './routes/about'
import { Route as UserLayoutImport } from './routes/$user/layout'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as UserIndexImport } from './routes/$user/index'
import { Route as UserRepositoriesIndexImport } from './routes/$user/repositories/index'
import { Route as UserGistsIndexImport } from './routes/$user/gists/index'
import { Route as UserRepositoriesRepoIndexImport } from './routes/$user/repositories/$repo/index'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const UserLayoutRoute = UserLayoutImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLayoutRoute,
} as any)

const UserRepositoriesIndexRoute = UserRepositoriesIndexImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => UserLayoutRoute,
} as any)

const UserGistsIndexRoute = UserGistsIndexImport.update({
  id: '/gists/',
  path: '/gists/',
  getParentRoute: () => UserLayoutRoute,
} as any)

const UserRepositoriesRepoIndexRoute = UserRepositoriesRepoIndexImport.update({
  id: '/repositories/$repo/',
  path: '/repositories/$repo/',
  getParentRoute: () => UserLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$user': {
      id: '/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof UserLayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/$user/': {
      id: '/$user/'
      path: '/'
      fullPath: '/$user/'
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof UserLayoutImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/$user/gists/': {
      id: '/$user/gists/'
      path: '/gists'
      fullPath: '/$user/gists'
      preLoaderRoute: typeof UserGistsIndexImport
      parentRoute: typeof UserLayoutImport
    }
    '/$user/repositories/': {
      id: '/$user/repositories/'
      path: '/repositories'
      fullPath: '/$user/repositories'
      preLoaderRoute: typeof UserRepositoriesIndexImport
      parentRoute: typeof UserLayoutImport
    }
    '/$user/repositories/$repo/': {
      id: '/$user/repositories/$repo/'
      path: '/repositories/$repo'
      fullPath: '/$user/repositories/$repo'
      preLoaderRoute: typeof UserRepositoriesRepoIndexImport
      parentRoute: typeof UserLayoutImport
    }
  }
}

// Create and export the route tree

interface UserLayoutRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserGistsIndexRoute: typeof UserGistsIndexRoute
  UserRepositoriesIndexRoute: typeof UserRepositoriesIndexRoute
  UserRepositoriesRepoIndexRoute: typeof UserRepositoriesRepoIndexRoute
}

const UserLayoutRouteChildren: UserLayoutRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserGistsIndexRoute: UserGistsIndexRoute,
  UserRepositoriesIndexRoute: UserRepositoriesIndexRoute,
  UserRepositoriesRepoIndexRoute: UserRepositoriesRepoIndexRoute,
}

const UserLayoutRouteWithChildren = UserLayoutRoute._addFileChildren(
  UserLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$user': typeof UserLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/$user/': typeof UserIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$user/gists': typeof UserGistsIndexRoute
  '/$user/repositories': typeof UserRepositoriesIndexRoute
  '/$user/repositories/$repo': typeof UserRepositoriesRepoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/$user': typeof UserIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$user/gists': typeof UserGistsIndexRoute
  '/$user/repositories': typeof UserRepositoriesIndexRoute
  '/$user/repositories/$repo': typeof UserRepositoriesRepoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$user': typeof UserLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/$user/': typeof UserIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$user/gists/': typeof UserGistsIndexRoute
  '/$user/repositories/': typeof UserRepositoriesIndexRoute
  '/$user/repositories/$repo/': typeof UserRepositoriesRepoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$user'
    | '/about'
    | '/profile'
    | '/$user/'
    | '/auth'
    | '/$user/gists'
    | '/$user/repositories'
    | '/$user/repositories/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile'
    | '/$user'
    | '/auth'
    | '/$user/gists'
    | '/$user/repositories'
    | '/$user/repositories/$repo'
  id:
    | '__root__'
    | '/'
    | '/$user'
    | '/about'
    | '/profile'
    | '/$user/'
    | '/auth/'
    | '/$user/gists/'
    | '/$user/repositories/'
    | '/$user/repositories/$repo/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserLayoutRoute: typeof UserLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  ProfileRoute: typeof ProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserLayoutRoute: UserLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  ProfileRoute: ProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$user",
        "/about",
        "/profile",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$user": {
      "filePath": "$user/layout.tsx",
      "children": [
        "/$user/",
        "/$user/gists/",
        "/$user/repositories/",
        "/$user/repositories/$repo/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/$user/": {
      "filePath": "$user/index.tsx",
      "parent": "/$user"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/$user/gists/": {
      "filePath": "$user/gists/index.tsx",
      "parent": "/$user"
    },
    "/$user/repositories/": {
      "filePath": "$user/repositories/index.tsx",
      "parent": "/$user"
    },
    "/$user/repositories/$repo/": {
      "filePath": "$user/repositories/$repo/index.tsx",
      "parent": "/$user"
    }
  }
}
ROUTE_MANIFEST_END */
